@echo off
echo Starting Emergency SOS Development Servers...

echo Starting Backend Server...
start "Backend Server" cmd /k "cd backend && npm run dev"

echo Starting Frontend Server...
start "Frontend Server" cmd /k "cd frontend && npm start"

echo Both servers are starting in separate windows...
pause
